services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  ericyangg/dsci522-project:1528a44
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64