name: heart-failure-classification
channels:
- defaults
- conda-forge
dependencies:
- python=3.11.14
- ipykernel=6.31.0
- pandas=2.3.3
- requests=2.32.5
- seaborn=0.13.2
- matplotlib=3.10.6
- scikit-learn=1.7.2
- altair-all=5.4.1
- pandera=0.27.0
- numpy=1.26.4
- notebook=6.5.4
- ipykernel=6.31.0
- jupyterlab=4.0.2
- click=8.3.1
- quarto=1.5.57
- tabulate=0.9.0
- statsmodels=0.14.5
- pytest=8.4.2
- conda-lock=3.0.4
- make=4.4.1
- pip=25.3
- pip:
  - altair-ally==0.1.1
  - deepchecks==0.19.1
